Utah Haskell : September 17, 2015 (Thursday)

* themes

- client-side REST using [[http://www.serpentine.com/wreq][Wreq]]
- folds instead of explicit recursion
  - http://learnyouahaskell.com/higher-order-functions
    - scroll down/ search for 'Only folds and horses' (about 3/4 down)
  - https://www.cs.nott.ac.uk/~gmh/fold.pdf
    - sections 1 and 2
- CIS 194 homework 1 exercises 1 and 4
  - http://www.seas.upenn.edu/~cis194/hw/01-intro.pdf
  - use solutions to exercise 1 and a fold to implement exercise 4

* interaction

Participants use [[http://www.serpentine.com/wreq][Wreq]] to send messages to a web service we will have running.

The service will be running on a laptop plugged into a projector. It
will display what participants send.

The service responds to participant's messages by posing challenges.
The challenges are based on
- getting info from Wreq responses
- folds (from the material above)
- CIS 194 exercises (above)

Participants send (text-representations of) solutions to the challenges.

Participants can also send questions.  Everything sent is displayed.

'wreq' requests should be sent to
- [[http://127.0.0.1:3000]]
- note: the localhost address will be replaced in the meeting

Example:

#+begin_example
curl -i 127.0.0.1:3000     -X POST -d '{ "name": "H", "msgId": 0, "txt": "greetings!" }'
#+end_example

* instructions

** clone repo

#+BEGIN_EXAMPLE
git clone git@github.com:haroldcarr/utah-haskell.git
#+END_EXAMPLE

Suggest: *only* look at =2015-09-17-template= (the other directories contain answers).

** download dependencies

This assumes you have [[https://github.com/commercialhaskell/stack][stack]] installed (as shown in our first meeting: [[http://seanhess.github.io/2015/08/04/practical-haskell-getting-started.html][getting started with stack]])

#+BEGIN_EXAMPLE
# go to directory that was cloned
cd utah-haskell

# go to this meeting's project
cd 2015-09-17-template

# build the template (this causes dependencies to be downloaded)
stack build

# if experiencing from GHC version mismatch error, please do: stack setup
# this may take a while... after it completes, continue with: stack build
#+END_EXAMPLE

** OPTIONAL : build/run the service

Do this if you want to experiment in advance of the meeting.
For the meeting we will have this service running.

#+BEGIN_EXAMPLE
# go to directory that was cloned
cd utah-haskell

# service location
cd infrastructure

# build the service (and download dependencies)
stack build

# run the service
stack exec utah-haskell-exe &
#+END_EXAMPLE

The service receives requests at [[http://127.0.0.1:3000]]

The service displays (i.e., point your browser to) request/responses at [[http://127.0.0.1:8023]]

** communicate with the service

*** via curl

#+begin_example
curl -i 127.0.0.1:3000     -X POST -d '{ "name": "H", "msgId": 0, "txt": "greetings!" }'
#+end_example

*** via ghci

*This is where the exercise /really/ begins.*

Start ghci:

#+BEGIN_EXAMPLE
cd utah-haskell
cd 2015-09-17-template
stack ghci
#+END_EXAMPLE

Enter the following into ghci:

#+BEGIN_EXAMPLE
:set -XOverloadedStrings
import Control.Lens
import Network.Wreq
import Data.Aeson (decode, toJSON)
import Data.Aeson.Lens (key)
import Data.Maybe (fromJust)
#+END_EXAMPLE

Now you can send messages to the services.

In ghci, instances of =Msg= are created via:

#+BEGIN_EXAMPLE
let outMsg = Msg "Your Name" 0 "some message text"
#+END_EXAMPLE

In ghci, a haskell representation of JSON is created via:

#+BEGIN_EXAMPLE
let jsn = toJSON outMsg
#+END_EXAMPLE

Messages to the service can be sent (and responses captured in =r=) via:

#+BEGIN_EXAMPLE
r <- post "http://127.0.0.1:3000" jsn
#+END_EXAMPLE

The response can be examined using techniques shown in the Wreq tutorial:

#+BEGIN_EXAMPLE
r ^? responseBody
r ^? responseBody . key "txt"

let (Just m)   = r ^? responseBody
let (Just inMsg) = (decode m) :: (Maybe Msg)
#+END_EXAMPLE

The =txt= field in the service response will contain a "challenge"
- enter that challenge into ghci
- grab ghci's response
- create a =Msg=
  - with the same =msgId= as the challenge =msgId=
  - with ghci's response as the =txt= field
- send that =Msg= to the service
  - if your answer is correct the service will issue a new challenge
  - else it will issue the same challenge again

Note: remember to (un)escape string quotes where appropriate.
